org: watheia
app: bean-counter-v0
service: greeting-service
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-jest-plugin
  - serverless-stack-output

package:
  individually: true

custom:
  stage: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: 8080
    lambdaPort: 7080
    noPrependStageInUrl: true
  bundle:
    linting: false
    tsConfig: 'tsconfig.app.json'
    esbuild: true
  output:
    handler: src/handlers/handler.greeting
    file: .serverless/stack.json

params:
  prod:
    production: true
  default:
    production: false

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: ${self:custom.stage}
  endpointType: REGIONAL
  timeout: 20
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps

functions:
  greet:
    handler: src/handlers/handler.greet
    events:
      - http:
          method: GET
          path: /greet
